name: Deploy to Sakura Rental Server

on:
  push:
    branches:
      - main  # メインブランチにプッシュされた時に実行

jobs:
  deploy:
    name: Deploy to Sakura via SFTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18 # 使用するNode.jsのバージョン

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build # Viteのビルドコマンド

      - name: Verify build output
        run: ls -al ./dist/ # ビルド結果を確認

      - name: Deploy to Sakura via SFTP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          source: ./dist/ # ローカルビルドフォルダ
          target: ${{ secrets.FTP_REMOTE_PATH }} # サーバー上のアップロード先ディレクトリ
          port: 22 # SFTPのポート（通常22）
          debug: true
          strip-components: 1 # dist フォルダを除外し中身のみ配置
